spring.application.name=barapp-backend
server.port=${PORT:8081}
spring.datasource.url=jdbc:postgresql://localhost:5432/barapp
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# DEV only: let Hibernate create/update schema
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
